name: Hello World
on: [ push ]
jobs:
  Hello-World-Job:
    runs-on: codebuild-codebuild-runner-cross-build-exer-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: |
          curl -fLO https://github.com/sbt/sbt/releases/download/v1.9.9/sbt-1.9.9.zip
          unzip sbt-1.9.9.zip
          mkdir /tmp/.sbt
          ln -s /tmp/.sbt ~/.sbt 
          ./sbt/bin/sbt --version