name: Hello World
on: [ push ]
jobs:
  Hello-World-Job:
    runs-on: codebuild-codebuild-runner-cross-build-exer-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: |
          curl -fL https://github.com/VirtusLab/coursier-m1/releases/latest/download/cs-aarch64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup
          ./cs install sbt
          sbt --version