name: Hello World
on: [ push ]
jobs:
  Hello-World-Job:
    runs-on: codebuild-codebuild-runner-cross-build-exer-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo yum install -y clang llvm clang-libs glibc-static libstdc++ libstdc++-devel
          curl -fLO https://github.com/sbt/sbt/releases/download/v1.9.9/sbt-1.9.9.zip
          unzip sbt-1.9.9.zip
          ./sbt/bin/sbt nativeLink
          ./target/scala-3.4.1/cross-build-exercise